default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['FOO_DB_USER'] %>
  password: <%= ENV['FOO_DB_PASSWORD'] %>
  host: <%= ENV['FOO_DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['FOO_DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['FOO_DB_TEST'] %>